/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela.Apoio;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Scheibel
 */
public class DlgSucesso extends javax.swing.JDialog {
  
    JFrame jFrame = new JFrame();
    JInternalFrame jIFrame = new JInternalFrame();
    JDialog jDialog = new JDialog();
    int status = 0;
    /**
     * Creates new form DlgErro
     */
    //status = 1
    public DlgSucesso(String aviso, JFrame tela, int statuss) {
        initComponents();
        JlabelAviso.setText("Sucesso ao " + aviso);
        jFrame = tela;
        status = statuss;
        setModal(true);
        this.setLocationRelativeTo(null);
    }
    
    //status = 2
    public DlgSucesso(String aviso, JDialog tela, int statuss) {
        initComponents();
        JlabelAviso.setText("Sucesso ao " + aviso);
        jDialog = tela;
        status = statuss;
        setModal(true);
        this.setLocationRelativeTo(null);
    }
    
    //status = 3
    public DlgSucesso(String aviso, JInternalFrame tela, int statuss) {
        initComponents();
        JlabelAviso.setText("Sucesso ao " + aviso);
        jIFrame = tela;
        status = statuss;
        setModal(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFechar = new javax.swing.JButton();
        JlabelAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aviso");

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        JlabelAviso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(JlabelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(JlabelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFechar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
     
        if(status == 1){
            if(jFrame != null){
                jFrame.setLocationRelativeTo(this);
                jFrame.setVisible(true); 
            } else {
                jIFrame.setVisible(true);
            }
        } else if(status == 2){
            if(jDialog != null){
                jDialog.setLocationRelativeTo(this);
                jDialog.setVisible(true); 
            } else {
                jDialog.setVisible(true);
            }
        } else if(status == 3){
            if(jIFrame != null){
                jIFrame.setVisible(true); 
            } else {
                jIFrame.setVisible(true);
            }
        }   
    }//GEN-LAST:event_jButtonFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelAviso;
    private javax.swing.JButton jButtonFechar;
    // End of variables declaration//GEN-END:variables
}
