package Entidade;
// Generated 03/08/2019 20:15:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private int id;
     private Estado estado;
     private String descricao;
     private Set fornecedors = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(int id) {
        this.id = id;
    }
    public Cidade(int id, Estado estado, String descricao, Set fornecedors) {
       this.id = id;
       this.estado = estado;
       this.descricao = descricao;
       this.fornecedors = fornecedors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }




}


