package Entidade;
// Generated 03/08/2019 20:15:02 by Hibernate Tools 4.3.1


import com.sun.istack.internal.NotNull;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @NotNull()
    @OneToOne()
    @JoinColumn(name = "estado_id", nullable = false)
    private Estado estado;
    
    @Column(name="id", length = 45)
    private String descricao;

    public Cidade() {
    }

	
    public Cidade(int id) {
        this.id = id;
    }
    public Cidade(int id, Estado estado, String descricao) {
       this.id = id;
       this.estado = estado;
       this.descricao = descricao;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
}


