package Entidade;
// Generated 03/08/2019 20:15:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set cidades = new HashSet(0);
     private Set fornecedors = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int id) {
        this.id = id;
    }
    public Estado(int id, String descricao, Set cidades, Set fornecedors) {
       this.id = id;
       this.descricao = descricao;
       this.cidades = cidades;
       this.fornecedors = fornecedors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }




}


