package Entidade;
// Generated 03/08/2019 20:15:02 by Hibernate Tools 4.3.1

import com.sun.istack.internal.NotNull;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;




/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
     
    @NotNull()
    @OneToOne()
    @JoinColumn(name = "cidade_id", nullable = false)
     private Cidade cidade;
    
    @NotNull()
    @OneToOne()
    @JoinColumn(name = "estado_id", nullable = false)
    private Estado estado;
    
    @NotNull()
    @Column(name = "razao_social", length = 100)
    private String razaoSocial;
    
    @Column(name = "nome_fantasia", length = 100)
    private String nomeFantasia;
    
    @NotNull()
    @Column(name = "cnpj")
    private Integer cnpj;
    
    @NotNull()
    @Column(name = "telefone")
    private Integer telefone;

    public Fornecedor() {
    }

	
    public Fornecedor(int id) {
        this.id = id;
    }
    public Fornecedor(int id, Cidade cidade, Estado estado, String razaoSocial, String nomeFantasia, Integer cnpj, Integer telefone) {
       this.id = id;
       this.cidade = cidade;
       this.estado = estado;
       this.razaoSocial = razaoSocial;
       this.nomeFantasia = nomeFantasia;
       this.cnpj = cnpj;
       this.telefone = telefone;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public Integer getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(Integer cnpj) {
        this.cnpj = cnpj;
    }
    public Integer getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Integer telefone) {
        this.telefone = telefone;
    }




}


