package Entidade;
// Generated 03/08/2019 20:15:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material")
public class Material  implements java.io.Serializable {

     @Id
     @Column(name="id")
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer id;
     
     @Column(name = "descricao", length = 100)
     private String descricao;
     
     @Column(name = "tipo", length = 100)
     private String tipo;
     
     @Column(name = "tamanho", length = 20)
     private String tamanho;
     
     @Column(name = "aplicacao", length = 100)
     private String aplicacao;
     
     @Column(name = "preco", precision = 10)
     private BigDecimal preco;

    public Material() {
    }

	
    public Material(int id) {
        this.id = id;
    }
    public Material(Integer id, String descricao, String tipo, String tamanho, String aplicacao, BigDecimal preco) {
       this.id = id;
       this.descricao = descricao;
       this.tipo = tipo;
       this.aplicacao = aplicacao;
       this.preco = preco;
       this.tamanho = tamanho;
    }

    @Override
    public String toString() {
        return "Material{" + "id=" + id + ", descricao=" + descricao + ", tipo=" + tipo + ", tamanho=" + tamanho + ", aplicacao=" + aplicacao + ", preco=" + preco + '}';
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getAplicacao() {
        return this.aplicacao;
    }
    
    public void setAplicacao(String aplicacao) {
        this.aplicacao = aplicacao;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    
    public String getTamanho() {
        return tamanho;
    }

    public void setTamanho(String tamanho) {
        this.tamanho = tamanho;
    }
}


