/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import DAO.AmbienteDAO;
import DAO.AmbienteFaceDAO;
import DAO.CamadaDAO;
import DAO.FaceDAO;
import DAO.ProjetoDAO;
import Entidade.Ambiente;
import Entidade.Face;
import Entidade.Projeto;
import Entidade.Usuario;

/**
 *
 * @author Scheibel
 */
public class JIFrameAmbiente extends javax.swing.JDialog {

    Usuario usuario = new Usuario();
    Projeto projetoEditar = new Projeto();
    Ambiente ambienteEditar = new Ambiente();
    Integer idAmbienteEditar;
    Integer idFaceEditar;
    /**
     * Creates new form JIFrameProjeto
     */
    public JIFrameAmbiente(Usuario usuarios) {
        initComponents();
        setModal(true);
        jTabbedPaneProjeto.setEnabled(false);
        jLabelProjeto.setText("Cadastro de Ambiente");
        this.setVisible(true);
        usuario = usuarios;
    }
    
    public JIFrameAmbiente(Usuario usuarios, Projeto projeto) {
        initComponents();
        usuario = usuarios;
        projetoEditar = projeto;
        setModal(true);
        jTabbedPaneProjeto.setEnabled(false);
        jLabelProjeto.setText("Edição de Ambiente");
        jTextFieldNomeProjeto.setText(projeto.getNome());
        jTextAreaDescricaoProjeto.setText(projeto.getDescricao());
        this.setVisible(true);       
    }
    
    public JIFrameAmbiente() {}
    
    public void AvancarListaAmbiente(Projeto projeto){
        jTabbedPaneProjeto.setSelectedIndex(1);
        jTabbedPaneProjeto.setTitleAt(1, "Lista de Ambientes");
        new AmbienteDAO().popularTabela(jTableAmbiente, projeto.getId() != null ? projeto : new ProjetoDAO().ConsultarUltimo());
    }
    
    public void EditarAmbiente(Ambiente ambiente){
        jTextAreaDescricaoAmbiente.setText(ambiente.getDescricao());
        jTabbedPaneProjeto.setSelectedIndex(2);
        jTabbedPaneProjeto.setTitleAt(2, "Dados do Ambiente");
        ambienteEditar = ambiente;
    }
    
    public void AvancarFaces(){
        jTabbedPaneProjeto.setSelectedIndex(3);
        jTabbedPaneProjeto.setTitleAt(3, "Faces do Ambiente");
        new AmbienteFaceDAO().popularTabela(jTableFace);
    }
    
    public void SalvarFace(){
        jTabbedPaneProjeto.setSelectedIndex(3);
        jTabbedPaneProjeto.setTitleAt(4, "");
        new AmbienteFaceDAO().popularTabela(jTableFace);
    }
    
    public void AtualizarTabelaCamada(){
        new CamadaDAO().popularTabela(jTableCamada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneProjeto = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelProjeto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeProjeto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescricaoProjeto = new javax.swing.JTextArea();
        jButtonVoltarCadastro = new javax.swing.JButton();
        jButtonAvancarAmbiente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableAmbiente = new javax.swing.JTable();
        jButtonVoltarDadosProjeto = new javax.swing.JButton();
        jButtonAdicionarAmbiente = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButtonEditarAmbiente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescricaoAmbiente = new javax.swing.JTextArea();
        jButtonVoltarListaAmbiente = new javax.swing.JButton();
        jButtonAvancarFace = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableFace = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButtonAdicionarFace = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelFace = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDescricaoFace = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableCamada = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButtonAdicionarCamada = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonFace = new javax.swing.JButton();
        jButtonVoltarFace = new javax.swing.JButton();

        setTitle("Ambiente");

        jLabelProjeto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome: *");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Descrição: ");

        jTextAreaDescricaoProjeto.setColumns(20);
        jTextAreaDescricaoProjeto.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescricaoProjeto);

        jButtonVoltarCadastro.setText("Voltar");
        jButtonVoltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarCadastroActionPerformed(evt);
            }
        });

        jButtonAvancarAmbiente.setText("Proximo");
        jButtonAvancarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarAmbienteActionPerformed(evt);
            }
        });

        jLabel11.setText("Campos com (*) são obrigatórios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonVoltarCadastro)
                        .addGap(119, 119, 119)
                        .addComponent(jButtonAvancarAmbiente)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarCadastro)
                    .addComponent(jButtonAvancarAmbiente))
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPaneProjeto.addTab("Dados do Projeto", jPanel2);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Lista de Ambientes");

        jTableAmbiente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane7.setViewportView(jTableAmbiente);

        jButtonVoltarDadosProjeto.setText("Voltar");
        jButtonVoltarDadosProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarDadosProjetoActionPerformed(evt);
            }
        });

        jButtonAdicionarAmbiente.setText("Adicionar");
        jButtonAdicionarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAmbienteActionPerformed(evt);
            }
        });

        jButton10.setText("Remover");

        jButtonEditarAmbiente.setText("Editar");
        jButtonEditarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAmbienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButtonVoltarDadosProjeto)
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonAdicionarAmbiente)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonEditarAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton10))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarDadosProjeto)
                    .addComponent(jButtonAdicionarAmbiente)
                    .addComponent(jButton10)
                    .addComponent(jButtonEditarAmbiente))
                .addGap(46, 46, 46))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );

        jTabbedPaneProjeto.addTab("", jPanel6);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Ambiente");

        jLabel5.setText("Descrição:");

        jTextAreaDescricaoAmbiente.setColumns(20);
        jTextAreaDescricaoAmbiente.setRows(5);
        jScrollPane3.setViewportView(jTextAreaDescricaoAmbiente);

        jButtonVoltarListaAmbiente.setText("Voltar");
        jButtonVoltarListaAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarListaAmbienteActionPerformed(evt);
            }
        });

        jButtonAvancarFace.setText("Proximo");
        jButtonAvancarFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarFaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButtonVoltarListaAmbiente)
                                .addGap(102, 102, 102)
                                .addComponent(jButtonAvancarFace))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarListaAmbiente)
                    .addComponent(jButtonAvancarFace))
                .addGap(112, 112, 112))
        );

        jTabbedPaneProjeto.addTab("", jPanel3);

        jTableFace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableFace);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Faces");

        jButtonAdicionarFace.setText("Adicionar");
        jButtonAdicionarFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarFaceActionPerformed(evt);
            }
        });

        jButton5.setText("Remover");

        jButton6.setText("Finalizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Editar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButtonAdicionarFace)
                        .addGap(41, 41, 41)
                        .addComponent(jButton5)
                        .addGap(40, 40, 40)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton6)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarFace)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPaneProjeto.addTab("Faces do Ambiente", jPanel4);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel7.setText("Descrição:");

        jTextAreaDescricaoFace.setColumns(20);
        jTextAreaDescricaoFace.setRows(5);
        jScrollPane5.setViewportView(jTextAreaDescricaoFace);

        jTableCamada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTableCamada);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Camadas");

        jButtonAdicionarCamada.setText("Adicionar");
        jButtonAdicionarCamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarCamadaActionPerformed(evt);
            }
        });

        jButton8.setText("Remover");

        jButtonFace.setText("Salvar");
        jButtonFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFaceActionPerformed(evt);
            }
        });

        jButtonVoltarFace.setText("Voltar");
        jButtonVoltarFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarFaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabelFace, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButtonVoltarFace, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonAdicionarCamada, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFace, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelFace, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarFace)
                    .addComponent(jButtonAdicionarCamada)
                    .addComponent(jButton8)
                    .addComponent(jButtonFace))
                .addGap(20, 20, 20))
        );

        jTabbedPaneProjeto.addTab("Dados do Face", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPaneProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarFaceActionPerformed
        jTabbedPaneProjeto.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonVoltarFaceActionPerformed

    private void jButtonFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFaceActionPerformed
        Face face = new Face(idFaceEditar, jTextAreaDescricaoAmbiente.getText());
        new FaceDAO().SalvarFace(face, this, usuario);
    }//GEN-LAST:event_jButtonFaceActionPerformed

    private void jButtonAdicionarCamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarCamadaActionPerformed
        DlgCamada dlg = new DlgCamada(usuario, this);
        dlg.setVisible(true);
    }//GEN-LAST:event_jButtonAdicionarCamadaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonAdicionarFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarFaceActionPerformed
        AtualizarTabelaCamada();
        jTabbedPaneProjeto.setSelectedIndex(4);
        jTabbedPaneProjeto.setTitleAt(4, "Cadastro de Face");
        jLabelFace.setText("Cadastro de Face");
    }//GEN-LAST:event_jButtonAdicionarFaceActionPerformed

    private void jButtonAvancarFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarFaceActionPerformed
        Ambiente ambiente = new Ambiente(idAmbienteEditar, jTextAreaDescricaoAmbiente.getText(), projetoEditar != null ? projetoEditar : new ProjetoDAO().ConsultarUltimo());
        new AmbienteDAO().SalvarAmbiente(ambienteEditar != null ? ambienteEditar : ambiente, this, usuario);
    }//GEN-LAST:event_jButtonAvancarFaceActionPerformed

    private void jButtonVoltarListaAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarListaAmbienteActionPerformed
        jTabbedPaneProjeto.setSelectedIndex(1);
        jTabbedPaneProjeto.setTitleAt(2, "");
        new AmbienteDAO().popularTabela(jTableAmbiente, projetoEditar.getId() != null ? projetoEditar : new ProjetoDAO().ConsultarUltimo());
    }//GEN-LAST:event_jButtonVoltarListaAmbienteActionPerformed

    private void jButtonAvancarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarAmbienteActionPerformed
        Projeto projeto = new Projeto(projetoEditar.getId(), jTextFieldNomeProjeto.getText(), jTextAreaDescricaoProjeto.getText());
        new ProjetoDAO().SalvarProjeto(projeto, this, usuario);    
    }//GEN-LAST:event_jButtonAvancarAmbienteActionPerformed

    private void jButtonVoltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarCadastroActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarCadastroActionPerformed

    private void jButtonVoltarDadosProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarDadosProjetoActionPerformed
        jTabbedPaneProjeto.setSelectedIndex(0);
        jTabbedPaneProjeto.setTitleAt(1, "");
    }//GEN-LAST:event_jButtonVoltarDadosProjetoActionPerformed

    private void jButtonAdicionarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAmbienteActionPerformed
        jTabbedPaneProjeto.setSelectedIndex(2);
        jTabbedPaneProjeto.setTitleAt(2, "Dados do Ambiente");
    }//GEN-LAST:event_jButtonAdicionarAmbienteActionPerformed

    private void jButtonEditarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAmbienteActionPerformed
        Ambiente ambiente = new AmbienteDAO().ConsultarAmbiente((int)jTableAmbiente.getValueAt(jTableAmbiente.getSelectedRow(), 0));
        new AmbienteDAO().VerificarAmbiente(ambiente, this);
    }//GEN-LAST:event_jButtonEditarAmbienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonAdicionarAmbiente;
    private javax.swing.JButton jButtonAdicionarCamada;
    private javax.swing.JButton jButtonAdicionarFace;
    private javax.swing.JButton jButtonAvancarAmbiente;
    private javax.swing.JButton jButtonAvancarFace;
    private javax.swing.JButton jButtonEditarAmbiente;
    private javax.swing.JButton jButtonFace;
    private javax.swing.JButton jButtonVoltarCadastro;
    private javax.swing.JButton jButtonVoltarDadosProjeto;
    private javax.swing.JButton jButtonVoltarFace;
    private javax.swing.JButton jButtonVoltarListaAmbiente;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFace;
    private javax.swing.JLabel jLabelProjeto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPaneProjeto;
    private javax.swing.JTable jTableAmbiente;
    private javax.swing.JTable jTableCamada;
    private javax.swing.JTable jTableFace;
    private javax.swing.JTextArea jTextAreaDescricaoAmbiente;
    private javax.swing.JTextArea jTextAreaDescricaoFace;
    private javax.swing.JTextArea jTextAreaDescricaoProjeto;
    private javax.swing.JTextField jTextFieldNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
