/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Apoio.Calculo;
import DAO.AmbienteDAO;
import DAO.CamadaDAO;
import DAO.FaceDAO;
import DAO.ProjetoDAO;
import Entidade.Ambiente;
import Entidade.Camada;
import Entidade.Face;
import Entidade.Projeto;
import Entidade.Usuario;
import java.util.List;

/**
 *
 * @author Scheibel
 */
public class JIFrameAmbiente extends javax.swing.JDialog {

    Usuario usuario = new Usuario();
    Projeto projetoAtual = new Projeto();
    Ambiente ambienteAtual = new Ambiente();
    Face faceAtual = new Face();
    Integer ambienteEditarId = null;
    JIFrameProjeto jIFrameProjeto = new JIFrameProjeto();
    /**
     * Creates new form JIFrameAmbiente
     */
    public JIFrameAmbiente(JIFrameProjeto jif, Usuario usuarios) {
        initComponents();
        setModal(true);
        setLocationRelativeTo(this);
        jIFrameProjeto = jif;
        this.usuario = usuarios;
        jTabbedPaneProjeto.setEnabled(false);
        jLabelProjeto.setText("Dados do Projeto");
        this.setVisible(true);    
    }
    
    public JIFrameAmbiente(Usuario usuarios, Projeto projeto) {
        initComponents();
        jTabbedPaneProjeto.setEnabled(false);
        usuario = usuarios;
        projetoAtual = projeto;
        setModal(true);
        setLocationRelativeTo(this);
        jLabelProjeto.setText("Edição de Ambiente");
        jTextFieldNomeProjeto.setText(projeto.getNome());
        jTextAreaDescricaoProjeto.setText(projeto.getDescricao());
        this.setVisible(true);       
    }
    
    public JIFrameAmbiente() {}
    
    public void AvancarListaAmbiente(Projeto projeto){
        projetoAtual = projeto;
        jTabbedPaneProjeto.setSelectedIndex(1);
        jTabbedPaneProjeto.setTitleAt(1, "Lista de Ambientes");
        AtualizarTabelAmbiente(projeto.getId() != null ? projeto : new ProjetoDAO().ConsultarUltimo());
    }
    
    public void EditarAmbiente(Ambiente ambiente){
        jTextAreaDescricaoAmbiente.setText(ambiente.getDescricao());
        jTabbedPaneProjeto.setSelectedIndex(2);
        jTabbedPaneProjeto.setTitleAt(2, "Dados do Ambiente");
        ambienteEditarId = ambiente.getId();
    }
    
    public void AvancarListaFace(Ambiente ambiente){
        jTabbedPaneProjeto.setSelectedIndex(3);
        jTabbedPaneProjeto.setTitleAt(3, "Faces do Ambiente");
        new FaceDAO().popularTabela(jTableFace, ambiente);
    }
    
    public void SalvarFace(Face face){
        faceAtual = face;
        setTabelaCamada(true);
        new CamadaDAO().popularTabela(jTableCamada, face);
    }
        
    public void AtualizarTabelAmbiente(Projeto projeto){
        projetoAtual = projeto;
        new AmbienteDAO().popularTabela(jTableAmbiente, projeto);
        jTextAreaDescricaoProjeto.setText("");
    }
    
    public void AtualizarTabelaFace(Ambiente ambiente){
        faceAtual = null;
        new FaceDAO().popularTabela(jTableFace, ambiente);
        jTextAreaDescricaoAmbiente.setText("");
    }
    
    public void AtualizarTabelaCamada(Face face){
        new CamadaDAO().popularTabela(jTableCamada, face);
    }
    
    public void setTabelaCamada(boolean status){       
        jTableCamada.setEnabled(status);
        jButtonAdicionarCamada.setEnabled(status);
        jButtonRemoverCamada.setEnabled(status);
        jLabelCamada.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        jTabbedPaneProjeto = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelProjeto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeProjeto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescricaoProjeto = new javax.swing.JTextArea();
        jButtonVoltarCadastro = new javax.swing.JButton();
        jButtonAvancarAmbiente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableAmbiente = new javax.swing.JTable();
        jButtonVoltarDadosProjeto = new javax.swing.JButton();
        jButtonAdicionarAmbiente = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButtonEditarAmbiente = new javax.swing.JButton();
        jButtonSalvarAmbiente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescricaoAmbiente = new javax.swing.JTextArea();
        jButtonVoltarListaAmbiente = new javax.swing.JButton();
        jButtonAvancarFace = new javax.swing.JButton();
        jPanelListaFace = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableFace = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButtonAdicionarFace = new javax.swing.JButton();
        jButtonRemoverFace = new javax.swing.JButton();
        jButtonSalvarFaces = new javax.swing.JButton();
        jButtonEditarFace = new javax.swing.JButton();
        jPanelFace = new javax.swing.JPanel();
        jLabelDadosFace = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDescricaoFace = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonConfirmarDescricao = new javax.swing.JButton();
        jButtonVoltarFace = new javax.swing.JButton();
        jButtonSalvarFace = new javax.swing.JButton();
        jLabelCamada = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableCamada = new javax.swing.JTable();
        jButtonAdicionarCamada = new javax.swing.JButton();
        jButtonRemoverCamada = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldTemperaturaInterna = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTemperaturaExterna = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldMetrosQuadrado = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jRadioButtonParedeEnsolarada = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setTitle("Ambiente");

        jLabelProjeto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome: *");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Descrição: ");

        jTextAreaDescricaoProjeto.setColumns(20);
        jTextAreaDescricaoProjeto.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescricaoProjeto);

        jButtonVoltarCadastro.setText("Voltar");
        jButtonVoltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarCadastroActionPerformed(evt);
            }
        });

        jButtonAvancarAmbiente.setText("Proximo");
        jButtonAvancarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarAmbienteActionPerformed(evt);
            }
        });

        jLabel11.setText("Campos com (*) são obrigatórios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonVoltarCadastro)
                        .addGap(119, 119, 119)
                        .addComponent(jButtonAvancarAmbiente)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarCadastro)
                    .addComponent(jButtonAvancarAmbiente))
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPaneProjeto.addTab("Dados do Projeto", jPanel2);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Lista de Ambientes");

        jTableAmbiente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane7.setViewportView(jTableAmbiente);

        jButtonVoltarDadosProjeto.setText("Voltar");
        jButtonVoltarDadosProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarDadosProjetoActionPerformed(evt);
            }
        });

        jButtonAdicionarAmbiente.setText("Adicionar");
        jButtonAdicionarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAmbienteActionPerformed(evt);
            }
        });

        jButton10.setText("Remover");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButtonEditarAmbiente.setText("Editar");
        jButtonEditarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAmbienteActionPerformed(evt);
            }
        });

        jButtonSalvarAmbiente.setText("Salvar");
        jButtonSalvarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAmbienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButtonVoltarDadosProjeto)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdicionarAmbiente)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvarAmbiente)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarDadosProjeto)
                    .addComponent(jButtonAdicionarAmbiente)
                    .addComponent(jButtonEditarAmbiente)
                    .addComponent(jButton10)
                    .addComponent(jButtonSalvarAmbiente))
                .addGap(156, 156, 156))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(231, Short.MAX_VALUE)))
        );

        jTabbedPaneProjeto.addTab("", jPanel6);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Ambiente");

        jLabel5.setText("Descrição:");

        jTextAreaDescricaoAmbiente.setColumns(20);
        jTextAreaDescricaoAmbiente.setRows(5);
        jScrollPane3.setViewportView(jTextAreaDescricaoAmbiente);

        jButtonVoltarListaAmbiente.setText("Voltar");
        jButtonVoltarListaAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarListaAmbienteActionPerformed(evt);
            }
        });

        jButtonAvancarFace.setText("Avançar");
        jButtonAvancarFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarFaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(215, 215, 215)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButtonVoltarListaAmbiente)
                        .addGap(111, 111, 111)
                        .addComponent(jButtonAvancarFace)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarListaAmbiente)
                    .addComponent(jButtonAvancarFace))
                .addGap(172, 172, 172))
        );

        jTabbedPaneProjeto.addTab("", jPanel3);

        jTableFace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableFace);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Faces");

        jButtonAdicionarFace.setText("Adicionar");
        jButtonAdicionarFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarFaceActionPerformed(evt);
            }
        });

        jButtonRemoverFace.setText("Remover");
        jButtonRemoverFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverFaceActionPerformed(evt);
            }
        });

        jButtonSalvarFaces.setText("Salvar");
        jButtonSalvarFaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarFacesActionPerformed(evt);
            }
        });

        jButtonEditarFace.setText("Editar");
        jButtonEditarFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarFaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaFaceLayout = new javax.swing.GroupLayout(jPanelListaFace);
        jPanelListaFace.setLayout(jPanelListaFaceLayout);
        jPanelListaFaceLayout.setHorizontalGroup(
            jPanelListaFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaFaceLayout.createSequentialGroup()
                .addGroup(jPanelListaFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListaFaceLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButtonAdicionarFace, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonEditarFace, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonRemoverFace, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvarFaces, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelListaFaceLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelListaFaceLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelListaFaceLayout.setVerticalGroup(
            jPanelListaFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaFaceLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanelListaFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarFace)
                    .addComponent(jButtonEditarFace)
                    .addComponent(jButtonSalvarFaces)
                    .addComponent(jButtonRemoverFace))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPaneProjeto.addTab("", jPanelListaFace);

        jLabelDadosFace.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel7.setText("Descrição: *");

        jTextAreaDescricaoFace.setColumns(20);
        jTextAreaDescricaoFace.setRows(5);
        jScrollPane5.setViewportView(jTextAreaDescricaoFace);

        jButtonConfirmarDescricao.setText("Confirmar");
        jButtonConfirmarDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDescricaoActionPerformed(evt);
            }
        });

        jButtonVoltarFace.setText("Voltar");
        jButtonVoltarFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarFaceActionPerformed(evt);
            }
        });

        jButtonSalvarFace.setText("Salvar");
        jButtonSalvarFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarFaceActionPerformed(evt);
            }
        });

        jLabelCamada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCamada.setText("Materiais");

        jTableCamada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTableCamada);

        jButtonAdicionarCamada.setText("Adicionar");
        jButtonAdicionarCamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarCamadaActionPerformed(evt);
            }
        });

        jButtonRemoverCamada.setText("Remover");
        jButtonRemoverCamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverCamadaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Temperatura Interna: *");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Temperatura Externa: *");

        jFormattedTextFieldTemperaturaInterna.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jFormattedTextFieldTemperaturaExterna.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldTemperaturaExterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTemperaturaExternaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Metros Quadrado: *");

        jFormattedTextFieldMetrosQuadrado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel15.setText("Parede Ensolarada:");

        jLabel13.setText("Campos com (*) são obrigatórios");

        javax.swing.GroupLayout jPanelFaceLayout = new javax.swing.GroupLayout(jPanelFace);
        jPanelFace.setLayout(jPanelFaceLayout);
        jPanelFaceLayout.setHorizontalGroup(
            jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFaceLayout.createSequentialGroup()
                .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFaceLayout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFaceLayout.createSequentialGroup()
                                .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelFaceLayout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7))
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFaceLayout.createSequentialGroup()
                                        .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel15))
                                            .addGroup(jPanelFaceLayout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(2, 2, 2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelFaceLayout.createSequentialGroup()
                                        .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldMetrosQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jFormattedTextFieldTemperaturaInterna, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jFormattedTextFieldTemperaturaExterna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                                            .addComponent(jRadioButtonParedeEnsolarada))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFaceLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonConfirmarDescricao))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFaceLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButtonAdicionarCamada, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201)
                                .addComponent(jButtonRemoverCamada, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFaceLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButtonVoltarFace, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSalvarFace, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFaceLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFaceLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCamada)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDadosFace, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanelFaceLayout.setVerticalGroup(
            jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFaceLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelDadosFace, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jFormattedTextFieldMetrosQuadrado))
                .addGap(6, 6, 6)
                .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFaceLayout.createSequentialGroup()
                        .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTemperaturaExterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jFormattedTextFieldTemperaturaInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addComponent(jRadioButtonParedeEnsolarada))
                .addGap(4, 4, 4)
                .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jButtonConfirmarDescricao))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelCamada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarCamada)
                    .addComponent(jButtonRemoverCamada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanelFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarFace)
                    .addComponent(jButtonVoltarFace))
                .addGap(20, 20, 20))
        );

        jTabbedPaneProjeto.addTab("", jPanelFace);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPaneProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneProjeto)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarFaceActionPerformed
        AtualizarTabelaFace(ambienteAtual);
        jTextAreaDescricaoFace.setText("");
        jTabbedPaneProjeto.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonVoltarFaceActionPerformed

    private void jButtonSalvarFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarFaceActionPerformed
    
        double temperaturaInterna = faceAtual.getTemperaturaInterna();
        double temperaturaExterna = faceAtual.getTemperaturaExterna();
        
        double resistenciaExterna = faceAtual.getResistenciaExterna();
        double resistenciaInterna = faceAtual.getResistenciaInterna();
        List<Camada> camada = new CamadaDAO().ConsultarPorFace(faceAtual);
             
        double resistenciaTotal = new Calculo().ResistenciaTermica(resistenciaInterna, camada, resistenciaExterna); 
        double transmitanciaTermica = new Calculo().TransmitanciaTermica((float) resistenciaTotal);
            
        double temperaturaSolar = new Calculo().TemperaturaSolarAr(0.20, 511, 0.04);
        double metrosQuadrado = faceAtual.getMetrosQuadrado();
                    
        double densidadeFluxoCalor = 0;
        double fluxoCalor = 0;
        if(faceAtual.getParedeEnsolarada()){
            densidadeFluxoCalor = new Calculo().DensidadeFluxoComSol(transmitanciaTermica, temperaturaSolar, temperaturaInterna, temperaturaExterna);
            fluxoCalor = new Calculo().FluxoCalor(densidadeFluxoCalor, metrosQuadrado);                 
        } else {
            densidadeFluxoCalor = new Calculo().DensidadeFluxoSemSol(transmitanciaTermica, temperaturaInterna, temperaturaExterna);  
            fluxoCalor = new Calculo().FluxoCalor(densidadeFluxoCalor, metrosQuadrado);    
        }
              
        double fatorSolar = 0.87; //Valor de vidro tranparente simples, ajustar para receber valor de fator solar de tipos de vidro diferentes
        double radiacaoSolarIncidente = 715; //Valor referente ao vidro simples, ajustar para receber o valor especifica para cada tipo de vidro escolhido
        
        double densidadeFluxoCalorVidro = 0;
        double fluxoCalorVidro = 0;
        if(new CamadaDAO().ConsultarCamadaPorMaterial(faceAtual.getId(), "Vidro")){
            densidadeFluxoCalorVidro = new Calculo().DensidadeFluxoCalorVidro(transmitanciaTermica, temperaturaInterna, temperaturaExterna, fatorSolar, radiacaoSolarIncidente);  
            double metrosQuadradoVidro = new Calculo().MetroQuadradoVidro("Metros Quadrado do Vidro"); //Rever funcao
            fluxoCalorVidro = new Calculo().FluxoCalor(densidadeFluxoCalorVidro, metrosQuadradoVidro); 
        }
        
        Face face = new Face(faceAtual.getId(), 
                             jTextAreaDescricaoFace.getText(), 
                             resistenciaInterna,
                             resistenciaExterna,                      
                             resistenciaTotal, 
                             transmitanciaTermica, 
                             temperaturaInterna,
                             temperaturaExterna,
                             temperaturaSolar, 
                             metrosQuadrado,
                             densidadeFluxoCalor, 
                             fatorSolar,
                             radiacaoSolarIncidente,
                             fluxoCalor, 
                             faceAtual.getParedeEnsolarada(),
                             fluxoCalorVidro,
                             ambienteAtual);
        
        new FaceDAO().SalvarFace(face, this, usuario);
        
        AtualizarTabelaFace(ambienteAtual);
        jTabbedPaneProjeto.setSelectedIndex(3);
        jTabbedPaneProjeto.setTitleAt(4, "");
        jTextAreaDescricaoFace.setText("");
    }//GEN-LAST:event_jButtonSalvarFaceActionPerformed

    private void jButtonAdicionarCamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarCamadaActionPerformed
        DlgSelecionarMaterial dlg = new DlgSelecionarMaterial(this, usuario, faceAtual);
        dlg.setVisible(true);
    }//GEN-LAST:event_jButtonAdicionarCamadaActionPerformed

    private void jButtonSalvarFacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarFacesActionPerformed
        List<Face> faces = new FaceDAO().ConsultarPorAmbiente(ambienteAtual);        
        double transmitanciaTermica = new Calculo().ArCondicionado(faces, 3412);
        
        ambienteAtual.setTransmitanciaTermica(transmitanciaTermica);
        new AmbienteDAO().EditarAmbiente(ambienteAtual, this, usuario);
    }//GEN-LAST:event_jButtonSalvarFacesActionPerformed

    private void jButtonAdicionarFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarFaceActionPerformed
        setTabelaCamada(false);
        jTextAreaDescricaoFace.setText("");
        jFormattedTextFieldTemperaturaExterna.setText("");
        jFormattedTextFieldTemperaturaInterna.setText("");
        jFormattedTextFieldMetrosQuadrado.setText("");
        jRadioButtonParedeEnsolarada.setSelected(false);
        
        new CamadaDAO().popularTabela(jTableCamada, null);
        jTabbedPaneProjeto.setSelectedIndex(4);
        jTabbedPaneProjeto.setTitleAt(4, "Cadastro da Face");
        jLabelDadosFace.setText("Cadastro da Face");
    }//GEN-LAST:event_jButtonAdicionarFaceActionPerformed

    private void jButtonAvancarFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarFaceActionPerformed
        Ambiente ambiente = new Ambiente(ambienteEditarId, jTextAreaDescricaoAmbiente.getText(), 0, projetoAtual != null ? projetoAtual : new ProjetoDAO().ConsultarUltimo());
        ambienteAtual = ambiente;
        new AmbienteDAO().SalvarAmbiente(ambiente, this, usuario); 
    }//GEN-LAST:event_jButtonAvancarFaceActionPerformed

    private void jButtonVoltarListaAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarListaAmbienteActionPerformed
        jTabbedPaneProjeto.setSelectedIndex(1);
        jTabbedPaneProjeto.setTitleAt(2, "");
        new AmbienteDAO().popularTabela(jTableAmbiente, projetoAtual.getId() != null ? projetoAtual : new ProjetoDAO().ConsultarUltimo());
    }//GEN-LAST:event_jButtonVoltarListaAmbienteActionPerformed

    private void jButtonAvancarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarAmbienteActionPerformed
        Projeto projeto = new Projeto(projetoAtual.getId(), jTextFieldNomeProjeto.getText(), jTextAreaDescricaoProjeto.getText(), projetoAtual.getCargaTermica());
        new ProjetoDAO().SalvarProjeto(projeto, this, usuario); 
    }//GEN-LAST:event_jButtonAvancarAmbienteActionPerformed

    private void jButtonVoltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarCadastroActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarCadastroActionPerformed

    private void jButtonVoltarDadosProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarDadosProjetoActionPerformed
        jTabbedPaneProjeto.setSelectedIndex(0);
        jTabbedPaneProjeto.setTitleAt(1, "");
    }//GEN-LAST:event_jButtonVoltarDadosProjetoActionPerformed

    private void jButtonAdicionarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAmbienteActionPerformed
        jTabbedPaneProjeto.setSelectedIndex(2);
        jTabbedPaneProjeto.setTitleAt(2, "Dados do Ambiente");
    }//GEN-LAST:event_jButtonAdicionarAmbienteActionPerformed

    private void jButtonEditarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAmbienteActionPerformed
        Ambiente ambiente = new AmbienteDAO().ConsultarAmbiente((int)jTableAmbiente.getValueAt(jTableAmbiente.getSelectedRow(), 0));
        ambienteAtual = ambiente;
        new AmbienteDAO().VerificarAmbiente(ambiente, this);
    }//GEN-LAST:event_jButtonEditarAmbienteActionPerformed

    private void jButtonEditarFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarFaceActionPerformed
        setTabelaCamada(false);
        new CamadaDAO().popularTabela(jTableCamada, null);
        jTabbedPaneProjeto.setSelectedIndex(4);
        jTabbedPaneProjeto.setTitleAt(4, "Edição da Face");
        jLabelDadosFace.setText("Edição da Face");
        Face face = new FaceDAO().ConsultarFace((int)jTableFace.getValueAt(jTableFace.getSelectedRow(), 0));
        jTextAreaDescricaoFace.setText(face.getDescricao());
        jFormattedTextFieldTemperaturaExterna.setText(face.getTemperaturaExterna()+ "");
        jFormattedTextFieldTemperaturaInterna.setText(face.getTemperaturaInterna()+ "");
        jFormattedTextFieldMetrosQuadrado.setText(face.getMetrosQuadrado() + "");
        jRadioButtonParedeEnsolarada.setSelected(face.getParedeEnsolarada());
        faceAtual = face;
    }//GEN-LAST:event_jButtonEditarFaceActionPerformed

    private void jButtonRemoverFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverFaceActionPerformed
        Face face = new FaceDAO().ConsultarFace((int)jTableFace.getValueAt(jTableFace.getSelectedRow(), 0));
        new FaceDAO().ExcluirFace(face, usuario);        
    }//GEN-LAST:event_jButtonRemoverFaceActionPerformed

    private void jButtonConfirmarDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDescricaoActionPerformed
        double temperaturaExterna = Double.valueOf(jFormattedTextFieldTemperaturaExterna.getText().replaceAll(",", "."));
        double temperaturaInterna = Double.valueOf(jFormattedTextFieldTemperaturaInterna.getText().replaceAll(",", "."));
                
        double resistenciaExterna = 0.04;
        double resistenciaInterna = 0.13;
        double metroQuadrado = Double.valueOf(jFormattedTextFieldMetrosQuadrado.getText().replaceAll(",", "."));
            
        Face face = new Face(faceAtual == null ? null : faceAtual.getId(),
                             jTextAreaDescricaoFace.getText(), 
                             resistenciaInterna,
                             resistenciaExterna, 
                             metroQuadrado, 
                             jRadioButtonParedeEnsolarada.isSelected(), 
                             temperaturaInterna, 
                             temperaturaExterna,
                             ambienteEditarId != null ? new AmbienteDAO().ConsultarAmbiente(ambienteEditarId) : new AmbienteDAO().ConsultarUltimo());
        
        new FaceDAO().SalvarFace(face, this, usuario);      
    }//GEN-LAST:event_jButtonConfirmarDescricaoActionPerformed

    private void jButtonRemoverCamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverCamadaActionPerformed
        Camada camada = new CamadaDAO().ConsultarCamada((int)jTableCamada.getValueAt(jTableCamada.getSelectedRow(), 0));
        new CamadaDAO().ExcluirCamada(camada, usuario);
        AtualizarTabelaCamada(camada.getFace());
    }//GEN-LAST:event_jButtonRemoverCamadaActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Ambiente ambiente = new AmbienteDAO().ConsultarAmbiente((int)jTableAmbiente.getValueAt(jTableAmbiente.getSelectedRow(), 0));
        new AmbienteDAO().ExcluirAmbiente(ambiente, usuario);
        AtualizarTabelAmbiente(ambiente.getProjeto());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonSalvarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAmbienteActionPerformed
        List<Face> faces = new FaceDAO().ConsultarPorAmbiente(new AmbienteDAO().ConsultarPorProjeto(projetoAtual.getId()));
        double cargaTermica = new Calculo().CargaTermica(faces);
        projetoAtual.setCargaTermica(cargaTermica);
        new ProjetoDAO().SalvarProjeto(projetoAtual, this, usuario);  
//        jIFrameProjeto.AtualizarTabelaProjeto();
        this.dispose();
    }//GEN-LAST:event_jButtonSalvarAmbienteActionPerformed

    private void jFormattedTextFieldTemperaturaExternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTemperaturaExternaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTemperaturaExternaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButtonAdicionarAmbiente;
    private javax.swing.JButton jButtonAdicionarCamada;
    private javax.swing.JButton jButtonAdicionarFace;
    private javax.swing.JButton jButtonAvancarAmbiente;
    private javax.swing.JButton jButtonAvancarFace;
    private javax.swing.JButton jButtonConfirmarDescricao;
    private javax.swing.JButton jButtonEditarAmbiente;
    private javax.swing.JButton jButtonEditarFace;
    private javax.swing.JButton jButtonRemoverCamada;
    private javax.swing.JButton jButtonRemoverFace;
    private javax.swing.JButton jButtonSalvarAmbiente;
    private javax.swing.JButton jButtonSalvarFace;
    private javax.swing.JButton jButtonSalvarFaces;
    private javax.swing.JButton jButtonVoltarCadastro;
    private javax.swing.JButton jButtonVoltarDadosProjeto;
    private javax.swing.JButton jButtonVoltarFace;
    private javax.swing.JButton jButtonVoltarListaAmbiente;
    private javax.swing.JFormattedTextField jFormattedTextFieldMetrosQuadrado;
    private javax.swing.JFormattedTextField jFormattedTextFieldTemperaturaExterna;
    private javax.swing.JFormattedTextField jFormattedTextFieldTemperaturaInterna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCamada;
    private javax.swing.JLabel jLabelDadosFace;
    private javax.swing.JLabel jLabelProjeto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelFace;
    private javax.swing.JPanel jPanelListaFace;
    private javax.swing.JRadioButton jRadioButtonParedeEnsolarada;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPaneProjeto;
    private javax.swing.JTable jTableAmbiente;
    private javax.swing.JTable jTableCamada;
    private javax.swing.JTable jTableFace;
    private javax.swing.JTextArea jTextAreaDescricaoAmbiente;
    private javax.swing.JTextArea jTextAreaDescricaoFace;
    private javax.swing.JTextArea jTextAreaDescricaoProjeto;
    private javax.swing.JTextField jTextFieldNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
